use sys;

CREATE DATABASE BOOTCAMP_EX4;
use BOOTCAMP_EX4;

CREATE TABLE PLAYERS (
	PLAYER_ID INTEGER NOT NULL UNIQUE,
    GROUP_ID INTEGER NOT NULL
);

CREATE TABLE MATCHES (
	MATCH_ID INTEGER NOT NULL UNIQUE,
    FIRST_PLAYER INTEGER NOT NULL,
    SECOND_PLAYER INTEGER NOT NULL,
    FIRST_SCORE INTEGER NOT NULL,
    SECOND_SCORE INTEGER NOT NULL
);

INSERT INTO PLAYERS (PLAYER_ID, GROUP_ID)
	VALUES (20,2), (30, 1), (40, 3), (45, 1), (50, 2), (65, 1);

INSERT INTO MATCHES (MATCH_ID, FIRST_PLAYER, SECOND_PLAYER, FIRST_SCORE, SECOND_SCORE)
	VALUES (1, 30, 45, 10, 12),
		   (2, 20, 50, 5, 5),
           (13, 65, 45, 10, 10),
           (5, 30, 65, 3, 15),
           (42, 45, 65, 8, 4);

SELECT * FROM PLAYERS;
SELECT * FROM MATCHES;

 WITH COMBINE_RESULT AS (
	SELECT M1.FIRST_PLAYER AS PLAYER_ID, M1.FIRST_SCORE AS SCORE
    FROM MATCHES M1
    UNION ALL
    SELECT M2.SECOND_PLAYER AS PLAYER_ID, M2.SECOND_SCORE AS SCORE
    FROM MATCHES M2
), SUM_RESULT AS (
	SELECT PLAYER_ID, SUM(SCORE) AS SCORE
    FROM COMBINE_RESULT
    GROUP BY PLAYER_ID
), FULL_RESULT AS (
	SELECT P.GROUP_ID, P.PLAYER_ID, COALESCE(SR.SCORE, 0) AS SCORE
    FROM PLAYERS P LEFT JOIN SUM_RESULT SR
	ON P.PLAYER_ID = SR.PLAYER_ID
 ), HIGH_RESULT AS (
	SELECT GROUP_ID, MAX(SCORE) AS SCORE
	FROM FULL_RESULT
	GROUP BY GROUP_ID
    ORDER BY GROUP_ID
), FINAL_RESULT AS (
    SELECT FR.GROUP_ID, FR.SCORE, FR.PLAYER_ID
    FROM FULL_RESULT FR
    JOIN HIGH_RESULT HR ON FR.GROUP_ID = HR.GROUP_ID AND FR.SCORE = HR.SCORE
)

-- SELECT GROUP_ID, PLAYER_ID
-- FROM FINAL_RESULT
-- ORDER BY GROUP_ID;

-- SELECT * FROM HIGH_RESULT;
-- SELECT * FROM SUM_RESULT;
-- SELECT * FROM FULL_RESULT
-- ORDER BY GROUP_ID;
-- SELECT HR.GROUP_ID, FR.PLAYER_ID AS WINNER_ID
-- FROM HIGH_RESULT HR LEFT JOIN FULL_RESULT FR
-- ON HR.SCORE = FR.SCORE ;

 ,  G1 AS (
        SELECT HR.GROUP_ID AS GROUP_ID, FR.PLAYER_ID AS WINNER_ID
    FROM HIGH_RESULT HR, FULL_RESULT FR
    WHERE HR.SCORE = FR.SCORE AND HR.GROUP_ID = 1
    ORDER BY FR.PLAYER_ID ASC
    LIMIT 1
),   G2 AS (
        SELECT HR.GROUP_ID  AS GROUP_ID, FR.PLAYER_ID AS WINNER_ID
    FROM HIGH_RESULT HR, FULL_RESULT FR
    WHERE HR.SCORE = FR.SCORE AND HR.GROUP_ID = 2
    ORDER BY FR.PLAYER_ID ASC
    LIMIT 1
),        G3 AS (
        SELECT HR.GROUP_ID AS GROUP_ID, FR.PLAYER_ID AS WINNER_ID
    FROM HIGH_RESULT HR, FULL_RESULT FR
    WHERE HR.SCORE = FR.SCORE AND HR.GROUP_ID = 3
    ORDER BY FR.PLAYER_ID ASC
    LIMIT 1
)
SELECT * FROM G1
UNION ALL
SELECT * FROM G2
UNION ALL
SELECT * FROM G3;


